# Copyright 2025 XTX Markets Technologies Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later
FROM ubuntu:noble-20250910
LABEL org.opencontainers.image.source https://github.com/XTXMarkets/ternfs
RUN set -eu
RUN apt-get update
RUN apt-get install -y python3 gcc g++ clang lld make cmake ninja-build mandoc build-essential git fuse valgrind llvm wget rsync golang-go
RUN apt-get clean
ENV IN_TERN_BUILD_CONTAINER Y
